route:
    group_by: [Alertname]
    group_interval: 30s
    repeat_interval: 30s
    # Send all notifications to me.
    receiver: email-me
receivers:
- name: email-me
  email_configs:
  - send_resolved: true
    to: admin@deekshithsn.co.in
    from: admin@deekshithsn.co.in
    smarthost: smtpout.secureserver.net:587
    auth_username: "admin@deekshithsn.co.in"
    auth_identity: "admin@deekshithsn.co.in"
    auth_password: "Callbooking123"
    tls_config:
          insecure_skip_verify: true
